### ISSUE TITLE
Create_VM Script errors on Netbox 2.8.3

### ISSUE THREAD

**Issue by mahomedh** [netbox-community/reports#29]
As per the title, I am running Netbox v2.8.3 and tried to run the `create_vm.py` script but it failed with the error below:

```
An exception occurred: FieldError: Cannot resolve keyword 'family' into field. Choices are: address, created, custom_field_values, description, dns_name, id, interface, interface_id, last_updated, nat_inside, nat_inside_id, nat_outside, primary_ip4_for, primary_ip6_for, role, services, status, tagged_items, tags, tenant, tenant_id, vrf, vrf_id

Traceback (most recent call last):
  File "/opt/netbox/netbox/extras/scripts.py", line 408, in run_script
    output = script.run(**kwargs)
  File "/opt/netbox/netbox/scripts/create_vm.py", line 98, in run
    add_addr(data["primary_ip4"], 4)
  File "/opt/netbox/netbox/scripts/create_vm.py", line 78, in add_addr
    vrf=data.get("vrf"),
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.6/site-packages/cacheops/query.py", line 390, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/models/query.py", line 404, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1382, in _add_q
    check_filterable=check_filterable,
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/opt/netbox/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1484, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'family' into field. Choices are: address, created, custom_field_values, description, dns_name, id, interface, interface_id, last_updated, nat_inside, nat_inside_id, nat_outside, primary_ip4_for, primary_ip6_for, role, services, status, tagged_items, tags, tenant, tenant_id, vrf, vrf_id
```

I am not a python dev, so I just worked around this issue by commenting out lines 77 and 84 which removes this text:

```
family=addr.version,
```

I assume this might not be a backward compatible change, but someone who knows better will have to decide. I just wanted to highlight it.

**Comment by candlerb** [comment]
I expect this is due to this change in [2.8.0](https://github.com/netbox-community/netbox/releases/tag/v2.8.0):

> [#4081](https://github.com/netbox-community/netbox/issues/4081) - The family field has been removed from the Aggregate, Prefix, and IPAddress models. The field remains available in the API representations of these models, however the column has been removed from the database table.

**Comment by candlerb** [comment]
I don't think that's necessary: anyone who wants to use historical versions of netbox can look through git history for historical versions of these scripts.  I'm not even sure it was ever necessary to set family explicitly.
